---
- name: 'Update APT package cache'
  #action: apt update_cache=yes
  apt:
    update_cache: yes

- name: 'Upgrade APT and the OS to the lastest packages'
  apt:
    upgrade: dist
  notify: Reboot
